version: '3.8'

services:
  app:
    build: .
    container_name: import-assistant
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    # Aseg√∫rate de tener estas variables en tu archivo .env o configuradas en tu entorno de despliegue
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
